language: c

os:
  - linux
  - osx

cache:
  directories:
    # Cache for the gcc archives
    - $HOME/gcc-cache/

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then GCC_NAME="gcc-arm-none-eabi-7-2017-q4-major-mac.tar.bz2"; else GCC_NAME="gcc-arm-none-eabi-7-2017-q4-major-linux.tar.bz2"; fi
  - if test ! -e $HOME/gcc-cache/$GCC_NAME ; then wget "https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2017q4/$GCC_NAME" -O $HOME/gcc-cache/$GCC_NAME ; fi
  - tar -xf $HOME/gcc-cache/$GCC_NAME -C $HOME
  - export PATH=$PATH:$HOME/gcc-arm-none-eabi-7-2017-q4-major/bin

script:
  - make -C left clean && make -j2 -C left DEBUG=1
  - make -C left clean && make -j2 -C left DEBUG=0
  - make -C right/uhk60v1 clean && make -j2 -C right/uhk60v1 DEBUG=1
  - make -C right/uhk60v1 clean && make -j2 -C right/uhk60v1 DEBUG=0
  - make -C right/uhk60v2 clean && make -j2 -C right/uhk60v2 DEBUG=1
  - make -C right/uhk60v2 clean && make -j2 -C right/uhk60v2 DEBUG=0
  - make -C keycluster clean && make -j2 -C keycluster DEBUG=1
  - make -C keycluster clean && make -j2 -C keycluster DEBUG=0
  - make -C trackball clean && make -j2 -C trackball DEBUG=1
  - make -C trackball clean && make -j2 -C trackball DEBUG=0
  - make -C trackpoint clean && make -j2 -C trackpoint DEBUG=1
  - make -C trackpoint clean && make -j2 -C trackpoint DEBUG=0
